using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class Entity_lvch_mst : ScriptableObject
{	
	public List<Param> param = new List<Param> ();

	[System.SerializableAttribute]
	public class Param
	{
		
		public int id;
		public string typ;
		public int min;
		public int max;
		public int lv1;
		public int lv2;
		public int lv3;
		public int lv4;
		public int lv5;
		public int lv6;
		public int lv7;
		public int lv8;
		public int lv9;
		public int lv10;
		public int lv11;
		public int lv12;
		public int lv13;
		public int lv14;
		public int lv15;
		public int lv16;
		public int lv17;
		public int lv18;
		public int lv19;
		public int lv20;
		public int lv21;
		public int lv22;
		public int lv23;
		public int lv24;
		public int lv25;
		public int lv26;
		public int lv27;
		public int lv28;
		public int lv29;
		public int lv30;
		public int lv31;
		public int lv32;
		public int lv33;
		public int lv34;
		public int lv35;
		public int lv36;
		public int lv37;
		public int lv38;
		public int lv39;
		public int lv40;
		public int lv41;
		public int lv42;
		public int lv43;
		public int lv44;
		public int lv45;
		public int lv46;
		public int lv47;
		public int lv48;
		public int lv49;
		public int lv50;
		public int lv51;
		public int lv52;
		public int lv53;
		public int lv54;
		public int lv55;
		public int lv56;
		public int lv57;
		public int lv58;
		public int lv59;
		public int lv60;
		public int lv61;
		public int lv62;
		public int lv63;
		public int lv64;
		public int lv65;
		public int lv66;
		public int lv67;
		public int lv68;
		public int lv69;
		public int lv70;
		public int lv71;
		public int lv72;
		public int lv73;
		public int lv74;
		public int lv75;
		public int lv76;
		public int lv77;
		public int lv78;
		public int lv79;
		public int lv80;
		public int lv81;
		public int lv82;
		public int lv83;
		public int lv84;
		public int lv85;
		public int lv86;
		public int lv87;
		public int lv88;
		public int lv89;
		public int lv90;
		public int lv91;
		public int lv92;
		public int lv93;
		public int lv94;
		public int lv95;
		public int lv96;
		public int lv97;
		public int lv98;
		public int lv99;
		public int lv100;
	}
}